[workspace]
members = [ "gfs_lib_core",
            "gfs_lib_contract",
            "gfs_lib_portfolio",
            "gfs_lib_simulation",
            "gfs_lib_terms",
            "gfs_lib_terms_proc_macro",
            "gfs_lib_types",
]
exclude = []

resolver = "2"

