[workspace]
members = [
    "libs/lib_actus_types",
    "libs/lib_actus_terms",
    "libs/lib_actus_core",
    "libs/lib_actus_portfolio",
    "libs/lib_actus_risk_factor",
    "main",
    "playground"]
resolver = "2"

