[package]
name = "main"
version = "0.1.0"
edition = "2021"

[dependencies]
lib_actus_contract = { path = "../libs-rust/lib_actus_contract" }
lib_actus_types = { path = "../libs-rust/lib_actus_types" }


