pub mod macro_struct_f64;
pub mod macro_struct_bool;
pub mod macro_struct_isodatetime;
pub mod macro_struct_isoperiod;
pub mod macro_struct_isocycle;
pub mod macro_struct_vec_isodatetime;
pub mod macro_struct_vec_isocycle;
pub mod macro_struct_vec_f64;
pub mod macro_struct_string;